# Python 3.11をベースイメージとして使用
FROM python:3.11-slim

# 環境変数を設定
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# 作業ディレクトリを作成・設定
WORKDIR /app

# Flaskをインストール
RUN pip install --no-cache-dir Flask

# アプリケーションコードをコピー
COPY ./tests ./tests

# モックサーバーのポートを公開
EXPOSE 5001

# モックサーバーの起動コマンド
CMD ["python", "tests/mock_server.py"]
